### ISSUE TITLE
[Question/Enhancement] Scrapper

### ISSUE THREAD

**Issue by Goldenfreddy0703** [ObviusOwl/anime-metadata-cache-kodi#1]
Hi, this is not an issue at all but its just a question and probably an Enhancement, Ok so im kinda confused on how this works and i don't really understand how this works either but is there a possibility or a possible chance that you could make this scrapper addon a seren package provider? a4kScrapers is a package provider that has torrent links but i believe if your scapper addon could become a seren package provider, you basically made anime possibly for the people that use real debrid with seren. Is there a possibly chance or possibility you could make this Enhancement? Your basically the only one who updates on a regular basis and who had the ability to make this happen.

**Comment by ObviusOwl** [comment]
hey, sorry I'm busy with work at the moment and this plugin is nowhere near in the shape of being published. Without it's [web application](https://github.com/ObviusOwl/anime-metadata-cache), doing the real work, this plugin is pretty useless. The web application is still in an unfinished state and needs to be deployed manually.

**Comment by Goldenfreddy0703** [comment]
Oh okay well thank you for the information and sorry for bothering you.
